function [newData1 varargout] = ImportHOBOFile(fileName)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 19-Apr-2011 10:52:24

DELIMITER = ',';
HEADERLINE = 2;         %File format changed slightly 2011_07_14


if (nargin ~= 1)   
    [fname, fpath]= uigetfile('*.csv', 'Select HOBO file');
    temp = fname;
    fname = fullfile(fpath,fname);

else
    fname = fileName;
    temp = fname;
end

% Import the file
newData1 = importdata(fname, DELIMITER, HEADERLINE);




varargout = {temp};
end
