%Written by Alex Greis
%10/03/2007
%Last Updated: 10/08/2007
%For a given .txt file generated by Lifetime Data Acquisition in Two-Photon
    %read all data points from file
    %read all associated .dat files, calculate lifetimes, then PO2 values
    %write them into text file as new data column
    %Plot the data using plot2d (draw microvasculature as lines)
    %Average image file and overlay that onto the plot
    
function overlay_2p
%read in text file, import data into Matlab
[fileName,pathName] = uigetfile('*.txt','Select Lifetime Acquisition Data','c:\Data\');
fpath=strcat(pathName,fileName);
M = dlmread(fpath,',',2,0);

%Open Lifetime data and calculate lifetime/PO2
fpath2 = strrep(fpath, '.txt', '_LifeTime_1.dat');
str1 = '1.dat';
count = 1;
delay = 60e-6;     %seconds;

for (n=1:size(M,1))
    if (M(n,1)~=-1)
        %calculate lifetime, then PO2 with that lifetime, insert into M
        %--------------------------Copied/Modified from calclifetimes()--------------------------------------------
        [data, hdr] = read_lifetime(fpath2);

        delaySamps = fix(delay * hdr.sampRate);

        avgData = mean(reshape(data,hdr.sampsPerTrig, hdr.numTrigs),2);

        avgData = avgData(delaySamps+1:hdr.sampsPerTrig);

        time = ((0:(hdr.sampsPerTrig  -delaySamps -1)) * 1/(hdr.sampRate))';


        a = mean(avgData(numel(avgData)-50:numel(avgData)));
        b = max(avgData)-a;

        f_result = fit(time,avgData, 'a + (b * exp(-x/tau))',[a, b, 100e-6]);
        lifetime = f_result.m(3);
        %---------------------------------------------------------------------------------------------------------
        %calculate PO2 and put in data matrix;
        po2val = po2(lifetime);
        M(n,5)=lifetime;
        M(n,6)=po2val;
        %update file name
        count=count+1;
        str2 = int2str(count);
        str2 = strcat(str2,'.dat');
        fpath2 = strrep(fpath2,str1,str2);
        str1=str2;
    end
end

%Open image (.dat file),average, and draw it
%NOTE: Currently you must select desired image to overlay due to poor
%acquisition quality. When image quality increases, use a=avg_2p(fpath)

%fpath = strrep(fpath, 'txt', 'dat');
%a=avg_2p(fpath2);
a=avg_2p();
imagesc(a);
%Plot the data in the new txt file
hold on;
plot2d(M);
colormap bone;

%Save lifetime/PO2 values in another text file (same directory as original)
%Create a .txt file -needed to create new file (it doesn't format
%the matrix or insert 2 lines of text)
saveFile = strcat(pathName,fileName);
saveFile = strrep(saveFile,'.txt','_po2.txt');
save(saveFile,'M','-ASCII');
%get first 2 lines
fid = fopen(fpath);
file = textscan(fid, '%s', 'delimiter', '\n');
fclose(fid);
tempCell = file{1};
line1=tempCell{1};
line2=tempCell{2};
%write file (overwrite file created by save)
A=char(1,1);
A=line1;
dlmwrite(saveFile, A,'delimiter','','newline','pc');
A=line2;
dlmwrite(saveFile, A,'delimiter','','newline','pc','-append');
dlmwrite(saveFile, M,'newline','pc','-append');
clear lastfit;