%Written by Alex Greis

%Used to read mosaic image file generated by mosaic_2p, and give
%appropriate header information.

%Update History:

%2/4/2008
    %Function is completely operational

function[img,hdr]= read_mosaic_2p
%open file,read header--------------------
[fname,fpath]= uigetfile('*.raw','c:\Data\');
fpath=strcat(fpath,fname);

fid = fopen(fpath, 'rb');
slices = fread(fid, 1, 'float32');
yres = fread(fid, 1, 'float32');
xres = fread(fid, 1, 'float32');
offset = fread(fid, 1, 'float32');
hdr=struct('Slices',slices,'YRes',yres,'XRes',xres,'Offset',offset);
fclose(fid);

%Open file, jump to offset, read image data
fid = fopen(fpath, 'rb');
fseek(fid,128,'bof');

for(i=1:slices)         %slices
    for(j=1:yres)       %y
        for(k=1:xres)   %x
            img(j,k,i) = fread(fid, 1, 'float32');
        end 
    end
end



